### ISSUE TITLE
Can't build with GDC 4.9.0

### ISSUE THREAD

**Issue by DemiMarie** [gtkd-developers/GtkD#86]
Building with GDC 4.9.0 gives strange linker errors:

```
make[1]: Leaving directory `/home/demetri/archives/GtkD-2.3.2'
gdc demos/gtkD/TestWindow/TestTreeView1.o demos/gtkD/TestWindow/TestDrawingArea.o demos/gtkD/TestWindow/TestTreeView.o demos/gtkD/TestWindow/TestEntries.o demos/gtkD/TestWindow/TestScales.o demos/gtkD/TestWindow/TestAspectFrame.o demos/gtkD/TestWindow/TTextView.o demos/gtkD/TestWindow/TestThemes.o demos/gtkD/TestWindow/TEditableCells.o demos/gtkD/TestWindow/TestStock.o demos/gtkD/TestWindow/TestText.o demos/gtkD/TestWindow/TestWindow.o demos/gtkD/TestWindow/TestImage.o demos/gtkD/TestWindow/TestIdle.o  -o TestWindow -Xlinker -L. -Xlinker -lgtkd-2 -Xlinker -ldl -m64
demos/gtkD/TestWindow/TTextView.o:(.data._D40TypeInfo_E4gtkc10pangotypes11PangoWeight6__initZ[_D40TypeInfo_E4gtkc10pangotypes11PangoWeight6__initZ]+0x30): undefined reference to `_D4gtkc10pangotypes11PangoWeight6__initZ'
/usr/bin/ld: demos/gtkD/TestWindow/TestStock.o(.text+0x19): unresolvable R_X86_64_TPOFF32 relocation against symbol `_D4gtkc8gtktypes9StockDescAAya'
/usr/bin/ld: final link failed: Nonrepresentable section on output
collect2: error: ld returned 1 exit status
make: *** [TestWindow] Error 1
```
